
export const GET_IMAGE_DATA_START = `GET_IMAGE_DATA_START`;
export const GET_IMAGE_DATA_SUCCESS = `GET_IMAGE_DATA_SUCCESS`;
export const GET_IMAGE_DATA_FAILURE = `GET_IMAGE_DATA_FAILURE`;

export const GET_LAYOUT_DATA_START = `GET_LAYOUT_DATA_START`;
export const GET_LAYOUT_DATA_SUCCESS = `GET_LAYOUT_DATA_SUCCESS`;
export const GET_LAYOUT_DATA_FAILURE = `GET_LAYOUT_DATA_FAILURE`;
